---
parser: babel-eslint

plugins:
  - react
  - react-native
  - import

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-native/all
  - plugin:import/errors
  - plugin:import/warnings
  - llama
  - prettier

parserOptions:
  sourceType: 'module'
  ecmaFeatures:
    jsx: true

env:
  browser: true
  jest: true
  es6: true

rules:
  require-jsdoc: off
  import/no-named-as-default: off
  id-length:
    - error
    - min: 2
      exceptions:
      # Lodash gets a single character, why not Ramda?
      - R

  space-before-function-paren:
    - error
    - asyncArrow: always
      anonymous: always
      named: never
