language: node_js
node_js:
- 8
script:
- yarn test
- yarn lint
after_success: "./compile-app.sh"
env:
  global:
    secure: MCFsormAqCMxsQXOfFwAAD5QzY7eCvEYZMBA/cFJb1g6BP64ff3atoHjPwU+n7PjobHLfjB3j0xW0o0I9j3h4tit+j3a38FoYf93LossTi/4hpPcpdCschghzDiRJMi6ykoK5mQdcPFZeJ1ou+zcxqkYCDqfhdDEz2wVquNV1VKjCnwzc4qptuRzi9TbOlk8nFE1BZBzdZP9s6BJHi3YqYNnViMUEEIZBvPkj8yJd6ikb8foStTzVYWbTQnsjiLv9fQIFpOTjblLhwkV909h61oWLi/7X9FMmjeHlkYjRIT/XjWEN35vwhnc/1SQQRgoassTzZoDYgjQeCVWY2cD4qCbsKamw+GfPXJZgpL9Rc4de+EdCbFu7RLcGn6O5R/MkOfmvt5I8EeErIbKH7eOKFklvEnvtEq1l8teWBNBsXyuWv+cjazVR2RZtHQU9b/J5O5WayChz7rNjNLOoywZ/Kt3iGms2xbsn3epMUnCNx4Po8pcdotICaB0kdYW78zIxaZjWHikKJO1lGyVH8atVkPEUrsJU3gI683axNdhuk5Pvg2VhGitclecDzYnxkUL3wrHVMhIelh1nmBKZhlvPPTsNHZO7E7MozHiv2wOrRLXiK/3T+uPWWtk5z1ryU7JBxE+w27vpcsGFbiImHKoGHPK+XlTGtpGwwoOOggiM7c=
